import os
from dotenv import load_dotenv

load_dotenv(override=True)

__env = os.getenv

FLASK_ENV = __env('FLASK_ENV')
FLASK_APP = __env("FLASK_APP")
FLASK_PORT = int(__env("FLASK_PORT"))
FLASK_HOST = __env("FLASK_HOST")
FLASK_DEBUG = __env("FLASK_DEBUG")
MYSQL_DB_URI = __env("MYSQL_DB_URI")
MYSQL_DB_URI_TEST = __env("MYSQL_DB_URI_TEST")
MYSQL_DB = __env('MYSQL_DB')
MYSQL_DB_DEV = __env('MYSQL_DB_DEV')
FRONTEND_URL = __env('FRONTEND_URL')
ACCESS_TOKEN_EXPIRES_MINUTES = int(__env('ACCESS_TOKEN_EXPIRES_MINUTES'))
OTP_EXPIRY_TIME_IN_MINUTES = int(__env('OTP_EXPIRY_TIME_IN_MINUTES'))
REFRESH_TOKEN_EXPIRES_DAYS = int(__env('REFRESH_TOKEN_EXPIRES_DAYS'))
JWT_SECRET_KEY = __env('JWT_SECRET_KEY')
MYSQL_CURSORCLASS = __env('MYSQL_CURSORCLASS')
REDIS_HOST = __env('REDIS_HOST')
REDIS_PORT = __env('REDIS_PORT')
REDIS_PASSWORD = __env('REDIS_PASSWORD')
EMAIL = __env('EMAIL')
EMAIL_PASSWORD = __env('EMAIL_PASSWORD')
